##Energy to be awarded- format: <id>:<value>
energyValues:
  - '1:1'
  - '12:1'
  - '3:1'
  - '2:2'
  - '4:2'
  - '5:3'
  - '15:5'
  - '16:5'
  - '14:8'
  - '52:25'
  - '122:1000'

##If true, energy for player can not fall below 0.
decreaseLimit: false